name: tesseract-voila

dependencies:
  - python=3.8
  - conda-forge::ipywidgets==7.6.5
  - conda-forge::jupyter_core==4.8.1
  - conda-forge::jupytext==1.13.0
  - conda-forge::tesseract==4.1.1
  - conda-forge::voila==0.2.16
